# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mdl/izo5011/IkennaWorkSpace/SYSC_FPGA/ip/axi_interconnect/axi_interconnect.xci
# IP: The module: 'axi_interconnect' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/SYSC_FPGA/ip/axi_interconnect/axi_interconnect_impl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/SYSC_FPGA/ip/axi_interconnect/axi_interconnect_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/SYSC_FPGA/ip/axi_interconnect/axi_interconnect_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/mdl/izo5011/IkennaWorkSpace/SYSC_FPGA/ip/axi_interconnect/axi_interconnect.xci
# IP: The module: 'axi_interconnect' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/SYSC_FPGA/ip/axi_interconnect/axi_interconnect_impl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/SYSC_FPGA/ip/axi_interconnect/axi_interconnect_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/mdl/izo5011/IkennaWorkSpace/SYSC_FPGA/ip/axi_interconnect/axi_interconnect_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_interconnect'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
