onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group TOP /sim_tb_top/u_example_top/sys_rst
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_init_calib_complete
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_data_compare_error
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_sys_clk_p
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_sys_clk_n
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_act_n
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_adr
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_ba
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_bg
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_cke
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_odt
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_cs_n
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_ck_t
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_ck_c
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_reset_n
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_dm_dbi_n
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_dq
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_dqs_t
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_dqs_c
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_awready
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_awid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_awaddr
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_awlen
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_awsize
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_awburst
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_awvalid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_wready
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_wdata
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_wlast
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_wvalid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_bid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_bresp
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_bvalid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_bready
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_arready
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_arid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_araddr
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_arlen
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_arsize
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_arburst
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_arvalid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_rid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_rdata
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_rresp
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_rlast
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_rvalid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/axi_rready
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_rd_req
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_rd_req_id
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_rd_addr
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_rd_len
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_rd_req_ack
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_rd_data
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_rd_data_vld
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_rd_data_rdy
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_rd_cmpl
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_wr_req
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_wr_req_id
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_wr_addr
add wave -noupdate -group TOP -radix decimal /sim_tb_top/u_example_top/init_wr_len
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_wr_req_ack
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_wr_data
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_wr_data_vld
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_wr_data_rdy
add wave -noupdate -group TOP /sim_tb_top/u_example_top/init_wr_cmpl
add wave -noupdate -group TOP /sim_tb_top/u_example_top/ce
add wave -noupdate -group TOP /sim_tb_top/u_example_top/sys_rdy
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_addr
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_cmd
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_en
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_wdf_data
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_wdf_end
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_wdf_mask
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_wdf_wren
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_rd_data
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_rd_data_end
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_rd_data_valid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_rdy
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_app_wdf_rdy
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_clk
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_rst
add wave -noupdate -group TOP /sim_tb_top/u_example_top/dbg_clk
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_wr_rd_complete
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_aresetn
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_data_msmatch_err
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_write_err
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_read_err
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_test_cmptd
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_write_cmptd
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_read_cmptd
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_cmptd_one_wr_rd
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_awid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_awaddr
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_awlen
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_awsize
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_awburst
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_awcache
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_awprot
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_awvalid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_awready
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_wdata
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_wstrb
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_wlast
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_wvalid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_wready
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_bready
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_bid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_bresp
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_bvalid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_arid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_araddr
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_arlen
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_arsize
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_arburst
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_arcache
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_arvalid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_arready
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_rready
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_rid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_rdata
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_rresp
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_rlast
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_s_axi_rvalid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_cmp_data_valid
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_cmp_data
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_rdata_cmp
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_dbg_wr_sts_vld
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_dbg_wr_sts
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_dbg_rd_sts_vld
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_dbg_rd_sts
add wave -noupdate -group TOP /sim_tb_top/u_example_top/dbg_bus
add wave -noupdate -group TOP /sim_tb_top/u_example_top/c0_ddr4_reset_n_int
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_addr_rd_ack
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_addr_wr_ack
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_addr_wr_ackd
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_araddr
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_arburst
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_arid
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_arlen
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_arready
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_arsize
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_arvalid
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_awaddr
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_awburst
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_awid
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_awlen
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_awlen_r
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_awready
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_awsize
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_awvalid
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_bid
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_bready
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_bresp
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_bvalid
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_rdata
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_rid_m
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_rid_s
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_rlast
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_rlast_d
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_rready
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_rresp
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_rvalid
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_wdata
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_wlast
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_wr_ct
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_wready
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_wstrb
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/axi_wvalid
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_AXI_ADDR_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_AXI_BR_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_AXI_DATA_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_AXI_ID_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_AXI_LEN_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_AXI_RESP_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_AXI_SZ_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_AXI_WSTRB_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_INIT_ADDR_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_INIT_DATA_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_INIT_ID_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_INIT_LEN_WTH
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_NUM_RD_CLIENTS
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_NUM_TOTAL_CLIENTS
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/C_NUM_WR_CLIENTS
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/ce
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/clk
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_rd_addr
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_rd_cmpl
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_rd_data
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_rd_data_rdy
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_rd_data_vld
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_rd_len
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_rd_req
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_rd_req_ack
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_rd_req_id
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_wr_addr
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_wr_cmpl
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_wr_data
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_wr_data_rdy
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_wr_data_vld
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_wr_len
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_wr_req
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_wr_req_ack
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/init_wr_req_id
add wave -noupdate -group BRG /sim_tb_top/u_example_top/i0_cnn_layer_accel_axi_bridge/rst
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/ce
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/clk
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_rd_addr
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_rd_cmpl
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_rd_data
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_rd_data_rdy
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_rd_data_vld
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_rd_len
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_rd_req
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_rd_req_ack
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_rd_req_id
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_wr_addr
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_wr_cmpl
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_wr_data
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_wr_data_rdy
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_wr_data_vld
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_wr_len
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_wr_req
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_wr_req_ack
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/init_wr_req_id
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_accelCfg
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_FAS_complt_arr
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_FAS_time
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_max_sys_mem_trans
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_memory
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_next_rd_req_id
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_next_wr_req_id
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_num_sys_mem_rd_in_prog
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_num_sys_mem_wr_in_prog
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_QUAD_time
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_req_arr
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_start_time
add wave -noupdate -group CNN_Layer_AcceL_TOP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/m_total_sys_mem_trans
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/clk
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_adder_tree_rdv_count
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_AWP_complt_arr
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_co_high_watermark_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_complete
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_complete_ack
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_conv_out_fmt0_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_convMap_fifo_sz
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_dpth_count
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_FAS_id
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_FAS_time
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_five_cycles_later
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_four_cycles_later
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_im_addr
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_inMapAddr_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_inMapFetchAmt_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_inMapFetchCount
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_inMapFetchTotal_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl1x1_pad_bgn_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl1x1_pad_end_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl1x1_pding_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl1x1Addr_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl1x1BiasAddr_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl1x1BiasFetchCount
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl1x1BiasFetchTotal_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl1x1Depth_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl1x1FetchCount
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl1x1FetchTotal_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl3x3Addr_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl3x3BiasAddr_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl3x3BiasFetchCount
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl3x3BiasFetchTotal_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl3x3FetchCount
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl3x3FetchTotal_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl_1x1_bias_bram_sz
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl_1x1_bram_sz
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_krnl_count
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_last_CO_recvd
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_last_output
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_last_wrt
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_mem_mng
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_num_1x1_kernels_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_num_output_cols_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_num_output_rows_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_num_QUAD_cfgd
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_ob_dwc_fifo_sz
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_om_addr
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_opcode_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_outBuf_fifo_sz
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_outMapAddr_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_outMapStoreCount
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_outMapStoreFactor_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_outMapStoreTotal_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_output_depth_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_partMap_fifo_sz
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_partMapAddr_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_partMapFetchCount
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_partMapFetchTotal_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_pixelSeqAddr_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_pixSeqCfgFetchTotal_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_pm_addr
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_pm_fetch_amount_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_pm_low_watermark_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_prevMap_dwc_fifo_sz
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_prevMap_fifo_sz
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_prevMapAddr_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_prevMapFetchCount
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_prevMapFetchTotal_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_prog_factor
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_pv_addr
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_pv_fetch_amount_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_pv_low_watermark_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_QUAD_en_arr
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_res_high_watermark_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_resdMap_dwc_fifo_sz
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_resdMap_fifo_sz
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_resdMapAddr_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_resdMapFetchCount
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_resdMapFetchTotal_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_rm_addr
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_rm_fetch_amount_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_rm_low_watermark_cfg
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_start
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_start_ack
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_start_time
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_state
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_three_cycles_later
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_total_store_trans
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_trans_fifo
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_trans_no
add wave -noupdate -group FAS /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/FAS_0/m_two_cycles_later
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/clk
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_AWP_cfgd
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_AWP_id
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_en
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_FAS_id
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_mem_mng
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_next_req_id
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_num_QUADs_cfgd
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_num_trans_in_prog
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_primed
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_QUADs_cfgd_arr
add wave -noupdate -group AWP /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/m_trans
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/clk
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_cascade_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_conv_out_fmt0_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_crpd_input_row_end_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_crpd_input_row_start_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_en
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_ex_start_time
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_input_col
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_input_row
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_kernel3x3Depth_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_kernelDepth
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_krnl_count
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_last_res_wrtn
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_master_QUAD_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_num_3x3_kernels_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_num_expd_input_cols_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_num_expd_input_rows_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_num_input_cols_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_num_input_rows_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_num_output_cols_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_num_output_rows_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_num_outputs
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_numKernelCols_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_numKernelRows_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_output_col
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_output_count
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_output_depth_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_output_row
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_padding_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_pfb_count
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_primed
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_processing
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_QUAD_id
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_QUAD_time
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_res_fifo_sz
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_res_high_watermark_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_return_state
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_start_time
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_state
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_stride_cfg
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_stride_count
add wave -noupdate -group QUAD /sim_tb_top/u_example_top/i0_SYSC_FPGA/CNN_Layer_Accel/AWP_0/QUAD_0/m_upsmaple_cfg
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {11153782 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 216
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {866525 ps} {14211566 ps}
